---
- name: install ops tools (yum)
  yum: pkg={{ item }} state=present
  with_items:
    - "{{ ops_tools_yum_pkgs }}"
  become: True

- name: update pip
  command: pip install pip --upgrade

- name: install ops tools (pip)
  pip: name={{ item}} state=present
  with_items:
    - "{{ ops_tools_pip_pkgs }}"
  become: True
